### ISSUE TITLE
Cooldowns

### ISSUE THREAD

**Issue by mgejay** [Superior-Development/IcarusMod#103] opened 2015-05-17 08:45 UTC
Let's tackle this issue before it begins in the first public release of Superior Freedom or whatever you plan on calling it.

Command cooldowns, prevents multiple smites and mutes, etc.

This would most likely be done with HashMap

**Comment by GotNoFriends** [comment] 2015-05-17 12:26
1.3 release.

**Comment by Wild1145** [comment] 2015-05-17 13:19
Duplicate of #43

**Closed as completed** 2015-05-17 13:19 UTC
Labels: Duplicate, Enhancement
